MA-17897 ASoC: fsl_dsp: Support building as module
commit 0c99d876def2626fc9065126f1db605e230567f5 from
https://source.codeaurora.org/external/imx/linux-imx

Make fsl_dsp_cpu as a separate driver, otherwise below
build error will occur when set CONFIG_SND_SOC_FSL_DSP=m

    ld.lld: error: duplicate symbol: init_module
    >>> defined at fsl_dsp.c
    >>>            sound/soc/fsl/fsl_dsp.o:(init_module)
    >>> defined at fsl_dsp_cpu.c
    >>>            sound/soc/fsl/fsl_dsp_cpu.o:(.init.text+0x0)

Signed-off-by: Jindong <jindong.yue@nxp.com>
Reviewed-by: Shengjiu Wang <shengjiu.wang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>