LF-1011-14 ASoC: pcm: fix build error due to for_each_rtd_components API change
commit e5d7b60122e9d146d766848712358dbd3305c597 from
https://source.codeaurora.org/external/imx/linux-imx

API changed since
613fb50059cf ("ASoC: soc-core: remove snd_soc_rtdcom_list")

In file included from ../sound/soc/soc-pcm.c:25:
../sound/soc/soc-pcm.c: In function ‘soc_rtdcom_ack’:
../include/sound/soc.h:1153:12: warning: comparison between pointer and integer
 1153 |       ((i) < rtd->num_components) && ((component) = rtd->components[i]);\
      |            ^
../sound/soc/soc-pcm.c:2881:2: note: in expansion of macro ‘for_each_rtd_components’
 2881 |  for_each_rtd_components(rtd, rtdcom, component) {
      |  ^~~~~~~~~~~~~~~~~~~~~~~
../include/sound/soc.h:1153:68: error: array subscript is not an integer
 1153 |       ((i) < rtd->num_components) && ((component) = rtd->components[i]);\
      |                                                                    ^
../sound/soc/soc-pcm.c:2881:2: note: in expansion of macro ‘for_each_rtd_components’
 2881 |  for_each_rtd_components(rtd, rtdcom, component) {
      |  ^~~~~~~~~~~~~~~~~~~~~~~
../include/sound/soc.h:1154:10: error: increment of pointer to an incomplete type ‘struct snd_soc_rtdcom_list’
 1154 |       (i)++)
      |          ^~
../sound/soc/soc-pcm.c:2881:2: note: in expansion of macro ‘for_each_rtd_components’
 2881 |  for_each_rtd_components(rtd, rtdcom, component) {

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>