net: stmmac: fix a merge error in stmmac_main.c
Fix the following build error which is introduced in merge commits
ef48d3d353b6 ("Merge branch 'v5.10/standard/base' into v5.10/standard/x86") and
c552a743a2fe ("Merge branch 'v5.10/standard/base' into v5.10/standard/preempt-rt/x86").

linux-yocto/drivers/net/ethernet/stmicro/stmmac/stmmac_main.c: In function ‘stmmac_suspend’:
linux-yocto/drivers/net/ethernet/stmicro/stmmac/stmmac_main.c:7667:17: error: ‘ret’
undeclared (first use in this function); did you mean ‘net’?
 7667 |                 ret = priv->plat->remove_phy_conv(priv->mii,
      |                 ^~~
      |                 net
linux-yocto/drivers/net/ethernet/stmicro/stmmac/stmmac_main.c:7667:17: note: each
undeclared identifier is reported only once for each function it appears in
make[6]: *** [linux-yocto/scripts/Makefile.build:280: drivers/net/ethernet/stmicro/stmmac/stmmac_main.o] Error 1

Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>