drivers: mtd: fsl-quadspi: rename the fsl-quadspi driver name to fix name conflict
In kernel v5.10, S32G platform uses "fsl-quadspi" as the quadspi driver,
which is implemented in drivers/mtd/spi-nor/controllers/fsl-quadspi.c.
But there is a same name driver in drivers/spi/spi-fsl-qspi.c, so when
drivers registeration, there will be an error:

	Error: Driver 'fsl-quadspi' is already registered, aborting...

This patch is to fix it.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>