MLK-21876-10 gpu: drm: lcdif: fix headfile reference issue
commit 4b8a6afa4362a1c47510a7dafe4467d7a447bdf3 from
https://source.codeaurora.org/external/imx/linux-imx

  CC      drivers/gpu/drm/imx/lcdif/lcdif-crtc.o
../drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:26:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>