ASoC: imx: fix build failture
commit 68806dd19054e79c1597fc3c10579e5a61986ea0 from
https://source.codeaurora.org/external/imx/linux-imx

sound/soc/fsl/imx-pcm-dma-v2.c: In function ‘imx_pcm_preallocate_dma_buffer’:
sound/soc/fsl/imx-pcm-dma-v2.c:131:6: error: void value not ignored as it ought to be
ret = snd_pcm_lib_preallocate_pages(substream,
    ^
sound/soc/fsl/imx-pcm-dma-v2.c: In function ‘imx_pcm_free_dma_buffers’:
sound/soc/fsl/imx-pcm-dma-v2.c:144:2: error: void value not ignored as it ought to be
return snd_pcm_lib_preallocate_free(substream);
^
sound/soc/fsl/imx-pcm-dma-v2.c:145:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>