LF-1011-23 gpu: drm: bridge: dsim: update using of drm_panel_get_modes
commit c3bc9d06c741e2a3d823cac235f351880a7cb9d8 from
https://source.codeaurora.org/external/imx/linux-imx

API changed since:
0ce8ddd8e06d ("drm/panel: add drm_connector argument to get_modes()")

../drivers/gpu/drm/bridge/sec-dsim.c: In function ‘sec_mipi_dsim_connector_get_modes’:
../drivers/gpu/drm/bridge/sec-dsim.c:1798:9: error: too few arguments to function ‘drm_panel_get_modes’
 1798 |  return drm_panel_get_modes(dsim->panel);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>