mmc: core: Fix the 'err' undeclared compile failure in mmc_alloc_host()
There is a compile failture caused by commit
3b4009b49634 ("mmc: core: Don't allocate IDA for OF aliases").
When merging code, it conflicts with sdk kernel patch, "err" is not replaced by
"index", and some indents and "}" are lost.

build error:

drivers/mmc/core/host.c:449:3: error: 'err' undeclared (first use in this function)
|   449 |   err = ida_simple_get(&mmc_host_ida, alias_id,
|       |   ^~~
drivers/mmc/core/host.c:568:15: error: non-static declaration of 'mmc_free_host' follows static declaration
|   568 | EXPORT_SYMBOL(mmc_free_host);
|       |               ^~~~~~~~~~~~~
drivers/mmc/core/host.c:554:15: error: non-static declaration of 'mmc_remove_host' follows static declaration
|   554 | EXPORT_SYMBOL(mmc_remove_host);
|       |               ^~~~~~~~~~~~~~~

Signed-off-by: Jun Miao <jun.miao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>