usb: dwc3: core: Fix build issue on 32-bit platform
commit cfac93d1905a8818c805409be4b9cdec824a7a8e from
https://source.codeaurora.org/external/imx/linux-imx

The GCC C compiler generates code that calls functions in the libgcc
library to implement the / and % operations with 64-bit operands on
32-bit CPUs. However, the Linux kernel is not linked against the libgcc
library, so such code will fail to link when building code for a 32-bit
Linux kernel:
LD      .tmp_vmlinux.kallsyms1
arm-fsl-linux-gnueabi-ld.bfd: drivers/usb/dwc3/core.o: in function
`dwc3_core_init':
core.c:(.text+0x176c): undefined reference to `__aeabi_uldivmod'
arm-fsl-linux-gnueabi-ld.bfd: core.c:(.text+0x1778): undefined reference
to `__aeabi_uldivmod'
Fix it by use the DIV_ROUND_DOWN_ULL.

build warning on armv7:
../drivers/usb/dwc3/core.c: In function ‘dwc3_frame_length_adjustment’:
../drivers/usb/dwc3/core.c:339:18: warning: integer overflow in
expression of type ‘long int’ results in ‘-728182784’ [-Woverflow]
  339 |   temp = 125000L * 1000000000L;

Reviewed-by: Peter Chen <peter.chen@nxp.com>
Signed-off-by: Li Jun <jun.li@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>