MLK-21876-9 gpu: drm: dpu: fix build for next-20190524 upgrade
commit c800268231d3532fd1f3f230445b0b99343790e4 from
https://source.codeaurora.org/external/imx/linux-imx

Due to below commit:
05c452c115bf ("drm: Remove users of drm_format_num_planes")

../drivers/gpu/drm/imx/dpu/dpu-kms.c: In function ‘dpu_atomic_assign_plane_source_per_crtc’:
../drivers/gpu/drm/imx/dpu/dpu-kms.c:144:3: error: implicit declaration of function ‘drm_format_num_planes’ [-Werror=implicit-function-declaration]
   num_planes = drm_format_num_planes(fb->format->format);
   ^
../drivers/gpu/drm/imx/dpu/dpu-plane.c: In function ‘dpu_plane_atomic_check’:
../drivers/gpu/drm/imx/dpu/dpu-plane.c:313:2: error: implicit declaration of function ‘drm_format_num_planes’ [-Werror=implicit-function-declaration]
  if (drm_format_num_planes(fb->format->format) > 1) {

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>