ASoC: fsl: fix SND_SOC_FSL_RPMSG_I2S dependency issue
commit 77cc52a577b250317e14f8cc7d4751f508724c8a from
https://source.codeaurora.org/external/imx/linux-imx

IMX RPMSG is still not ready.

In file included from ../sound/soc/codecs/rpmsg_wm8960.c:27:0:
../sound/soc/codecs/../fsl/fsl_rpmsg_i2s.h:278:29: fatal error: linux/imx_rpmsg.h: No such file or directory
 #include <linux/imx_rpmsg.h>
                             ^
compilation terminated.
../scripts/Makefile.build:278: recipe for target 'sound/soc/codecs/rpmsg_wm8960.o' failed
make[4]: *** [sound/soc/codecs/rpmsg_wm8960.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  AR      arch/arm/mach-imx/built-in.a
In file included from ../sound/soc/codecs/rpmsg_cs42xx8.c:25:0:
../sound/soc/codecs/../fsl/fsl_rpmsg_i2s.h:278:29: fatal error: linux/imx_rpmsg.h: No such file or directory
 #include <linux/imx_rpmsg.h>

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>