vpu: hantro: fix build failure
commit d054a8308bae8de9760d318afe40bed010620052 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/mxc/hantro/hantrodec.c: In function ‘hantrodec_ioctl’:
../drivers/mxc/hantro/hantrodec.c:1033:62: error: macro "access_ok" passed 3 arguments, but takes just 2
   err = !access_ok(VERIFY_WRITE, (void *) arg, _IOC_SIZE(cmd));
                                                              ^
../drivers/mxc/hantro/hantrodec.c:1033:10: error: ‘access_ok’ undeclared (first use in this function)
   err = !access_ok(VERIFY_WRITE, (void *) arg, _IOC_SIZE(cmd));
          ^
../drivers/mxc/hantro/hantrodec.c:1033:10: note: each undeclared identifier is reported only once for each function it appears in
../drivers/mxc/hantro/hantrodec.c:1035:61: error: macro "access_ok" passed 3 arguments, but takes just 2
   err = !access_ok(VERIFY_READ, (void *) arg, _IOC_SIZE(cmd));
                                                             ^
  CC      drivers/mtd/nand/raw/nand_base.o
  CC      drivers/irqchip/irq-mvebu-odmi.o
  CC      drivers/mtd/nand/raw/nand_legacy.o
../drivers/mxc/hantro/hantrodec.c: In function ‘get_hantro_core_desc32’:
../drivers/mxc/hantro/hantrodec.c:1266:61: error: macro "access_ok" passed 3 arguments, but takes just 2
  if (!access_ok(VERIFY_READ, up, sizeof(struct core_desc_32)) ||
                                                             ^
../drivers/mxc/hantro/hantrodec.c:1266:7: error: ‘access_ok’ undeclared (first use in this function)
  if (!access_ok(VERIFY_READ, up, sizeof(struct core_desc_32)) ||
       ^
../drivers/mxc/hantro/hantrodec.c: In function ‘put_hantro_core_desc32’:
../drivers/mxc/hantro/hantrodec.c:1280:62: error: macro "access_ok" passed 3 arguments, but takes just 2
  if (!access_ok(VERIFY_WRITE, up, sizeof(struct core_desc_32)) ||
                                                              ^
../drivers/mxc/hantro/hantrodec.c:1280:7: error: ‘access_ok’ undeclared (first use in this function)
  if (!access_ok(VERIFY_WRITE, up, sizeof(struct core_desc_32)) ||
       ^
../scripts/Makefile.build:278: recipe for target 'drivers/mxc/hantro/hantrodec.o' failed
make[4]: *** [drivers/mxc/hantro/hantrodec.o] Error 1
../scripts/Makefile.build:489: recipe for target 'drivers/mxc/hantro' failed
make[3]: *** [drivers/mxc/hantro] Error 2
../scripts/Makefile.build:489: recipe for target 'drivers/mxc' failed
make[2]: *** [drivers/mxc] Error 2
make[2]: *** Waiting for unfinished jobs...

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>