Revert "phy: ti: j721e-wiz: Invoke wiz_init() before of_platform_device_create()"
This reverts commit 6115a9027e5294e2f38ff0efac7c34e8ee40a706.

Since this commit introduced a wrong merge which caused a compiling error.
And the previous commit c2409e3a56d7e8 (phy: ti: j721e-wiz: Don't configure wiz
if its already configured) has implemented to call wiz_init() before of_platform_device_create().
So drop this commit.

To fix below error building:
	drivers/phy/ti/phy-j721e-wiz.c:1128:3: error: label 'err_wiz_init' used but not defined
	DEBUG:	1128 |   goto err_wiz_init;
	1128 |   goto err_wiz_init;
	DEBUG:	|   ^~~~
	|   ^~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>