net: octeontx2: Fix compile error in function rvu_npc_init()
When upgrade kernel version, some code to resolve merge conflicts has been
submitted, will cause build issue. I found these code has been integrated
into function rvu_npc_setup_interfaces().
Delete these code to fix compile errors below.

drivers/net/ethernet/marvell/octeontx2/af/rvu_npc.c:2004:2: error: 'rx_kex'
undeclared (first use in this function)
   rx_kex = npc_mkex_default.keyx_cfg[NIX_INTF_RX];
   ^~~~~~
drivers/net/ethernet/marvell/octeontx2/af/rvu_npc.c:2005:2: error: 'tx_kex'
undeclared (first use in this function)
   tx_kex = npc_mkex_default.keyx_cfg[NIX_INTF_TX];
   ^~~~~~
drivers/net/ethernet/marvell/octeontx2/af/rvu_npc.c:2006:2: error: 'nibble_ena'
undeclared (first use in this function)
   nibble_ena = FIELD_GET(NPC_PARSE_NIBBLE, rx_kex);
   ^~~~~~~~~~

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>