LF-1011-2 arm64: dts: imx8mm-ddr4-evk-inmate: fix build break
commit 79e31c4b0c59bc00303b7eac595dbc25a7a35a08 from
https://source.codeaurora.org/external/imx/linux-imx

Remove memory node deletion due to below change:
e1437b09449a ("arm64: dts: imx8mm: Memory node should be in board DT")

Otherwise,met below error:
Error: ../arch/arm64/boot/dts/freescale/imx8mm-ddr4-evk-inmate.dts:69.15-34 Label or path /memory@40000000 not found
FATAL ERROR: Syntax error parsing input tree
scripts/Makefile.lib:302: recipe for target 'arch/arm64/boot/dts/freescale/imx8mm-ddr4-evk-inmate.dtb' failed
make[3]: *** [arch/arm64/boot/dts/freescale/imx8mm-ddr4-evk-inmate.dtb] Error 1
make[3]: *** Waiting for unfinished jobs....
Error: ../arch/arm64/boot/dts/freescale/imx8mq-evk.dts:227.1-6 syntax error

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>