MLK-21876-8 gpu: drm: dpu: fix build for next-20190524 upgrade
commit a0e5c7ae6eb802d807a188220d41b900017df5c8 from
https://source.codeaurora.org/external/imx/linux-imx

Due to below commit:
f3e9632cb624 ("drm: Remove users of drm_format_(horz|vert)_chroma_subsampling")

../drivers/gpu/drm/imx/dpu/dpu-plane.c: In function ‘drm_plane_state_to_uvbaseaddr’:
../drivers/gpu/drm/imx/dpu/dpu-plane.c:164:2: error: implicit declaration of function ‘drm_format_horz_chroma_subsampling’ [-Werror=implicit-function-declaration]
  x /= drm_format_horz_chroma_subsampling(fb->format->format);
  ^
../drivers/gpu/drm/imx/dpu/dpu-plane.c:165:2: error: implicit declaration of function ‘drm_format_vert_chroma_subsampling’ [-Werror=implicit-function-declaration]
  y /= drm_format_vert_chroma_subsampling(fb->format->format);
  ^

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>