LF-424 gpu/imx: lcdif: fix typo for imx_lcdif_dt_ids
commit f1d02bae297d231e9343f7e0da8256d3d93e9492 from
https://source.codeaurora.org/external/imx/linux-imx

When built the driver as module, this typo error can
be found by compiler with below build error reported:

In file included from drivers/gpu/imx/lcdif/lcdif-common.c:20:
drivers/gpu/imx/lcdif/lcdif-common.c:78:25: error: ‘lcdif_dt_ids’ undeclared here (not in a function); did you mean ‘imx_lcdif_dt_ids’?
   78 | MODULE_DEVICE_TABLE(of, lcdif_dt_ids);
      |                         ^~~~~~~~~~~~
./include/linux/module.h:227:15: note: in definition of macro ‘MODULE_DEVICE_TABLE’
  227 | extern typeof(name) __mod_##type##__##name##_device_table  \
      |               ^~~~
./include/linux/module.h:227:21: error: ‘__mod_of__lcdif_dt_ids_device_table’ aliased to undefined symbol ‘lcdif_dt_ids’
  227 | extern typeof(name) __mod_##type##__##name##_device_table  \
      |                     ^~~~~~
drivers/gpu/imx/lcdif/lcdif-common.c:78:1: note: in expansion of macro ‘MODULE_DEVICE_TABLE’
   78 | MODULE_DEVICE_TABLE(of, lcdif_dt_ids);
      | ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Fancy Fang <chen.fang@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>