uio: rename uio.c -> uio_core.c & unify into uio.ko
commit  6941ac307804c3a5c05dc64436a8c21904874bb9 from
https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.10

When uio_dmabuf.c was added, it broke building uio as a kmod.

The error is:
```
ERROR: "uio_dmabuf_unmap" [drivers/uio/uio.ko] undefined!
ERROR: "uio_dmabuf_map" [drivers/uio/uio.ko] undefined!
ERROR: "uio_dmabuf_cleanup" [drivers/uio/uio.ko] undefined!
```

Two kmods would be built: `uio.ko` & `uio_dmabuf.ko`.
The nasty part is that `uio.ko` would require symbols from `uio_dmabuf.ko`,
which isn't ideal since `uio.c` is the core part of the UIO subsystem.

Exporting the above symbols is not ideal either, because even if it fixes
the build, it fails at runtime with:
```
[    7.594314] uio_dmabuf: Unknown symbol dma_buf_get (err -2)
[    7.594344] uio_dmabuf: Unknown symbol dma_buf_put (err -2)
[    7.594412] uio_dmabuf: Unknown symbol dma_buf_detach (err -2)
[    7.639590] uio_dmabuf: Unknown symbol dma_buf_attach (err -2)
[    7.639636] uio_dmabuf: Unknown symbol dma_buf_map_attachment (err -2)
[    7.639673] uio_dmabuf: Unknown symbol dma_buf_unmap_attachment (err -2)
[    7.639712] uio_dmabuf: Unknown symbol dma_buf_get (err -2)
[    7.639742] uio_dmabuf: Unknown symbol dma_buf_put (err -2)
```

The simplest (and not necessarily the most ideal) fix is to rename `uio.c`
to `uio_core.c`, and make sure that `uio.ko` includes both sources into
that single kmod.
The alternative would have been to move all the code in the `uio.c` file.

And the other alternative would be to make sure that that `uio_dmabuf.ko`
can be more self-sufficient.

Fixes: de2151831d9 ("uio: Add dma-buf import ioctls")
Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
State: pending
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>