ASoC: fsl: imx-wm8958: fix build for 5.1 RC kernel
commit 69bef1118914e35146baf72149070908c13cc482 from
https://source.codeaurora.org/external/imx/linux-imx

../sound/soc/fsl/imx-wm8958.c: In function 'hpjack_status_check':
../sound/soc/fsl/imx-wm8958.c:88:3: error: implicit declaration of function 'snd_soc_codec_get_dapm' [-Werror=implicit-function-declaration]
   snd_soc_dapm_disable_pin(snd_soc_codec_get_dapm(priv->codec), "Ext Spk");
   ^
../sound/soc/fsl/imx-wm8958.c:88:3: warning: passing argument 1 of 'snd_soc_dapm_disable_pin' makes pointer from integer without a cast
In file included from ../include/sound/soc.h:413:0,
                 from ../sound/soc/fsl/imx-wm8958.c:19:
../include/sound/soc-dapm.h:449:5: note: expected 'struct snd_soc_dapm_context *' but argument is of type 'int'
 int snd_soc_dapm_disable_pin(struct snd_soc_dapm_context *dapm,
     ^
../sound/soc/fsl/imx-wm8958.c:92:3: warning: passing argument 1 of 'snd_soc_dapm_enable_pin' makes pointer from integer without a cast
   snd_soc_dapm_enable_pin(snd_soc_codec_get_dapm(priv->codec), "Ext Spk");
   ^
In file included from ../include/sound/soc.h:413:0,
                 from ../sound/soc/fsl/imx-wm8958.c:19:
../include/sound/soc-dapm.h:445:5: note: expected 'struct snd_soc_dapm_context *' but argument is of type 'int'
 int snd_soc_dapm_enable_pin(struct snd_soc_dapm_context *dapm,
     ^
../sound/soc/fsl/imx-wm8958.c: In function 'imx_hifi_hw_params':
../sound/soc/fsl/imx-wm8958.c:126:41: error: 'struct snd_soc_dai' has no member named 'codec'
  struct snd_soc_codec *codec = codec_dai->codec;
                                         ^
../sound/soc/fsl/imx-wm8958.c:210:2: error: implicit declaration of function 'snd_soc_update_bits' [-Werror=implicit-function-declaration]
  snd_soc_update_bits(codec, WM8994_GPIO_1, 0x1f, 0x2);
  ^
../sound/soc/fsl/imx-wm8958.c: In function 'imx_wm8958_gpio_init':
../sound/soc/fsl/imx-wm8958.c:292:41: error: 'struct snd_soc_dai' has no member named 'codec'
  struct snd_soc_codec *codec = codec_dai->codec;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>