LF-1011-28 ASoC: fsl: hdmi-dma: drop snd_soc_pcm_lib_ioctl
commit 73b27dee90eb0dee027a13f9edfc7084cf6a6131 from
https://source.codeaurora.org/external/imx/linux-imx

This ioctl was removed since:
e91f134c83b1 ("ASoC: sh: Drop superfluous ioctl PCM ops")

../sound/soc/fsl/imx-hdmi-dma.c:1088:12: error: ‘snd_soc_pcm_lib_ioctl’ undeclared here (not in a function); did you mean ‘snd_pcm_lib_ioctl’?
 1088 |  .ioctl  = snd_soc_pcm_lib_ioctl,
      |            ^~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>