MLK-21876-10 gpu: drm: lcdif: fix headfile reference issue
commit 7839dd863127d63ea95a0825a8221e31e3263fd9 from
https://source.codeaurora.org/external/imx/linux-imx

  CC      drivers/gpu/drm/imx/lcdif/lcdif-crtc.o
../drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:26:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>