MLK-15098: ASoC: fsl: fix imx-pcm build error when no dma
commit 37bfb6ded92f2b1e607f7c6cab627ae99b3518d1 from
https://source.codeaurora.org/external/imx/linux-imx

Fix build error when SOC_IMX_PCM_DMA is not enabled
error: expected identifier or ‘(’ before ‘{’ token})

Signed-off-by: Adrian Alonso <adrian.alonso@nxp.com>