aufs: fix compile failure when accessing rw_sem.owner in rt-kernel
rw_semaphore is implemented with rt-mutex in rt-kernel which is
different from the standard kernel. Compatible with these two
implementations on aufs by adding a "#ifndef" statement.

The compile failure log as blow:

|   CC      drivers/char/hw_random/virtio-rng.o
|   CC      kernel/task_work.o
|
/tmp-glibc/work-shared/intel-x86-64/kernel-source/fs/aufs/i_op.c:
In function 'au_pin_hdir_set_owner':
|
/tmp-glibc/work-shared/intel-x86-64/kernel-source/fs/aufs/i_op.c:636:52:
error: 'struct rw_semaphore' has no member named 'owne
r'
|   636 |         atomic_long_set(&p->hdir->hi_inode->i_rwsem.owner,
(long)task);
|       |                                                    ^
|   CC      arch/x86/video/fbdev.o
| make[3]: ***
[/tmp-glibc/work-shared/intel-x86-64/kernel-source/scripts/Makefile.build:279:
fs/aufs/i_op.o] Error 1
| make[3]: *** Waiting for unfinished jobs....
|   CC      drivers/acpi/acpica/nsinit.o
|   CC      kernel/extable.o
|   AR      net/ipv4/built-in.a

Signed-off-by: Yanfei Xu <yanfei.xu@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>