MLK-24874-2: include: uapi: mxc_dsp: fix the UAPI_HEADER_TEST failure
commit 215ccb3784f2c8abb930e789e262e9bf98489c83 from
https://source.codeaurora.org/external/imx/linux-imx

Enable CONFIG_UAPI_HEADER_TEST turns out the following build issues:

HDRTEST usr/include/linux/mxc_dsp.h
In file included from <command-line>:32:0:
./usr/include/linux/mxc_dsp.h:82:2: error: C++ style comments are not allowed in ISO C90
  //UNIA_CHANNEL_MASK,
  ^
./usr/include/linux/mxc_dsp.h:82:2: error: (this will be reported only once per input file)

The fix is to use C style comment insteading of C++

Signed-off-by: Jason Liu <jason.hui.liu@nxp.com>
(cherry picked from commit 4c016b8114b3db2bba7ec579c34e248766feac6e)
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>