MLK-24795-1: mm: cma: export symbol for driver to build module
commit 04cdbc715258b7273480402740308e6fc334a18c from
https://source.codeaurora.org/external/imx/linux-imx

If driver invoking these functions and want to build as a module, these
functions need export symbol. Without this patch, will meet below errors
when build our driver module:

ERROR: "cma_for_each_area" [drivers/misc/mic/imx-host/imx_mic_host.ko] undefined!
ERROR: "cma_get_name" [drivers/misc/mic/imx-host/imx_mic_host.ko] undefined!

Signed-off-by: Joakim Zhang <qiangqing.zhang@nxp.com>
Signed-off-by: Sherry Sun <sherry.sun@nxp.com>
Reviewed-by: Frank Li <Frank.Li@nxp.com>
Reviewed-by: Fugang Duan <fugang.duan@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>