MLK-21876-3 clk: imx7ulp: fix build for next-20190524 upgrade
commit 979c0306d270fbeef3c37d92dd084a15de392ab6 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/clk/imx/clk-composite-7ulp.c: In function ‘imx7ulp_clk_composite’:
../drivers/clk/imx/clk-composite-7ulp.c:83:3: error: implicit declaration of function ‘readl_relaxed’ [-Werror=implicit-function-declaration]
   val = readl_relaxed(reg);
   ^
../drivers/clk/imx/clk-composite-7ulp.c:85:3: error: implicit declaration of function ‘writel_relaxed’ [-Werror=implicit-function-declaration]
   writel_relaxed(val, reg);
   ^
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>