rpmsg: imx: include slab.h explicitly
commit b2432a6607694e81fa6709338b7d453a91ce70a7 from
https://source.codeaurora.org/external/imx/linux-imx

To fix build issues of:
error: implicit declaration of function ‘kmalloc’
error: implicit declaration of function ‘kfree’

Signed-off-by: Li Yang <leoyang.li@nxp.com>