MLK-21876-10 gpu: drm: ipu: fix headfile reference issue (part2)
commit 3b8360aaa409c2dbff0d618475e4b7caadaf9e39 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>