MLK-15098: ASoC: fsl: fix imx-pcm build error when no dma
commit 98ee74727894da0250d31c0f43038016aa1f24e8 from
https://source.codeaurora.org/external/imx/linux-imx

Fix build error when SOC_IMX_PCM_DMA is not enabled
error: expected identifier or ‘(’ before ‘{’ token})

Signed-off-by: Adrian Alonso <adrian.alonso@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>