LF-1011-26 arm: imx: pm-imx7: fix build break when calling of_flat_dt_match
commit d90990a61b6ce6d963d4728b4871ae5b249d11d2 from
https://source.codeaurora.org/external/imx/linux-imx

Old API was hiddened from user.

../arch/arm/mach-imx/pm-imx7.c: In function ‘imx7_dt_find_lpsram’:
../arch/arm/mach-imx/pm-imx7.c:891:6: error: implicit declaration of function ‘of_flat_dt_match’ [-Werror=implicit-function-declaration]
  891 |  if (of_flat_dt_match(node, low_power_ocram_match)) {
      |      ^~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>