LF-1011-13 gpu: drm: dsim: fix build break due to API change
commit f0e848cf9abbe3f385b3aa1cdaa22bc170500779 from
https://source.codeaurora.org/external/imx/linux-imx

Struct bridge was removed from struct encoder since below commit:
05193dc38197 ("drm/bridge: Make the bridge chain a double-linked list")

  CC      drivers/gpu/drm/imx/sec_mipi_dsim-imx.o
../drivers/gpu/drm/imx/sec_mipi_dsim-imx.c: In function ‘imx_sec_dsim_encoder_helper_atomic_check’:
../drivers/gpu/drm/imx/sec_mipi_dsim-imx.c:113:37: error: ‘struct drm_encoder’ has no member named ‘bridge’
  113 |  struct drm_bridge *bridge = encoder->bridge;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>