vpu: windsor: remove deprecated using of VB2_BUF_STATE_PREPARED
commit 7737a541ccdca04f4dd8c9303df16787897e8c8d from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/mxc/vpu_windsor/vpu_encoder_b0.c: In function ‘show_buffer_info’:
../drivers/mxc/vpu_windsor/vpu_encoder_b0.c:4001:21: error: ‘VB2_BUF_STATE_PREPARED’ undeclared (first use in this function)
    " %d:prepared,", VB2_BUF_STATE_PREPARED);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>