MLK-21876-10 gpu: drm: dpu: fix headfile reference issue (part 1)
commit 3948cdacdf38c83d891f3bc499144830eb61f274 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>