LF-665-4 input: mma8450: fix build break
commit 5409daabcc477353e0b3f3f6f347971efb0d3ca9 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/input/misc/mma8450.c: In function 'mma8450_probe':
../drivers/input/misc/mma8450.c:156:6: error: redeclaration of 'err' with no linkage
  int err, client_id;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>