ASoC: SOF: imx8m: Add missing headers for using regmap
commit 8d67634f735877322ee9989f2a176b88d6a5b417 from
https://source.codeaurora.org/external/imx/linux-imx

This fixes the following compilation error:

sound/soc/sof/imx/imx8m.c:340:17: error: implicit declaration of function
‘syscon_regmap_lookup_by_compatible’ [-Werror=implicit-function-declaration]
priv->regmap = syscon_regmap_lookup_by_compatible("fsl,imx8mp-audio-blk-ctrl");
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sound/soc/sof/imx/imx8m.c:340:15: warning: assignment to ‘struct regmap
*’ from ‘int’ makes pointer from integer without a cast [-Wint-convers
ion]

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>