include: uapi: xlnx_tsmux: fix hdrtest failure due to unknown type name
When enabling CONFIG_UAPI_HEADER_TEST, there will be compile error as
below:

In file included from <command-line>:32:
./usr/include/linux/xlnx_mpg2tsmux_interface.h:59:2: error: unknown type name ‘u8’
   59 |  u8 stream_id;
      |  ^~

There is no u8/u16/u32/u64/bool definition in uapi headers. So we need
use __u8/__u16/__u32/__u64 which defined in include/uapi/linux/types.h.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>