MLK-13470 mfd: max17135: export symbols to fix build error as a module
commit f5c206b5393d3c48fa56ad963381bda0405e89c7 from
https://source.codeaurora.org/external/imx/linux-imx

export symbols to fix build error as a module:

ERROR: "max17135_reg_read" [drivers/hwmon/max17135-hwmon.ko] undefined!

Signed-off-by: Julien Olivain <julien.olivain@nxp.com>
Acked-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>