LF-1197-2 gpu: drm: imx: ipuv3: remove drmP.h
commit 3b8360aaa409c2dbff0d618475e4b7caadaf9e39 from
https://source.codeaurora.org/external/imx/linux-imx

API changes:
4e98f871bcff ("drm: delete drmP.h + drm_os_linux.h")

drivers/gpu/drm/imx/ipuv3/ipuv3-kms.c:15:10: fatal error: drm/drmP.h: No such file or directory
   15 | #include <drm/drmP.h>

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>