uapi: fix linux/rpmsg_rpc.h userspace compilation errors
commit e305e42944b8d9427675398ca2272f36770c390a from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

The uapi rpmsg_rpc.h header file generates a whole bunch
of userspace compilation errors with allmodconfig and when
using ARM GCC 9.2-2019.12 compiler:

./usr/include/linux/rpmsg_rpc.h:19:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:20:2: error: unknown type name ‘int32_t’
./usr/include/linux/rpmsg_rpc.h:72:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:73:2: error: unknown type name ‘ptrdiff_t’
./usr/include/linux/rpmsg_rpc.h:74:2: error: unknown type name ‘size_t’
./usr/include/linux/rpmsg_rpc.h:75:2: error: unknown type name ‘int32_t’
./usr/include/linux/rpmsg_rpc.h:92:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:93:2: error: unknown type name ‘size_t’
./usr/include/linux/rpmsg_rpc.h:94:2: error: unknown type name ‘size_t’
./usr/include/linux/rpmsg_rpc.h:95:2: error: unknown type name ‘size_t’
./usr/include/linux/rpmsg_rpc.h:96:2: error: unknown type name ‘int32_t’
./usr/include/linux/rpmsg_rpc.h:114:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:115:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:117:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:127:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:128:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:174:2: error: unknown type name ‘uint16_t’
./usr/include/linux/rpmsg_rpc.h:175:2: error: unknown type name ‘uint16_t’
./usr/include/linux/rpmsg_rpc.h:176:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:177:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:178:2: error: unknown type name ‘int32_t’
./usr/include/linux/rpmsg_rpc.h:179:2: error: unknown type name ‘uint32_t’
./usr/include/linux/rpmsg_rpc.h:180:2: error: unknown type name ‘uint8_t’

Fix these by switching the integer types uint8_t, uint16_t, uint32_t and
int32_t to the types from linux/types.h __u8, __u16, __u32 and __s32
respectively, and including the proper userspace headers.

Fixes: b7540e45bf1c ("rpmsg: rpc: introduce a new rpmsg_rpc driver")
Signed-off-by: Suman Anna <s-anna@ti.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>