PCI: j721e: disable retrain Link for Gen2 training
The quirk_retrain_flag = true is to retrain link for Gen2 training,
however this will cause LINKDOWN and below call trace, here set the flag
to false to fix this issue.

ERROR:   Unhandled External Abort received on 0x80000000 from S-EL1
ERROR:   exception reason=0 syndrome=0xbf000000
Unhandled Exception from EL1
x0             = 0xfffffe0018ab0000
x1             = 0x0000000000000000
x2             = 0xfffffe001a400008
x3             = 0x0000000000000001
x4             = 0x000000000000000b
x5             = 0xfffffc0805588000
x6             = 0xfffffc08010ae130
x7             = 0x0000000000000000
x8             = 0xfffffe0012e66c28
x9             = 0xfffffe00109ad980
x10            = 0x0000000006aa84f3
x11            = 0x00000000000c0266
x12            = 0xfffffc0805aa829a
x13            = 0xfffffc0805aa8a1c
x14            = 0xffffffffffffffff
x15            = 0xfffffc08010adc98
x16            = 0x0000000000000002
x17            = 0x0000000000000001
x18            = 0x0000000000000020
x19            = 0xfffffe00149cf734
x20            = 0x0000000000000004
x21            = 0xfffffc080418b000
x22            = 0x0000000000000087
x23            = 0xfffffe00149cf7e4
x24            = 0x0000000000000000
x25            = 0xfffffe0012d5aea8
x26            = 0x0000000000000001
x27            = 0xfffffc0805588000
x28            = 0xfffffc080418b000
x29            = 0xfffffe00149cf6b0
x30            = 0xfffffe001097dbd4
scr_el3        = 0x000000000000073d
sctlr_el3      = 0x0000000030cd183f
cptr_el3       = 0x0000000000000000
tcr_el3        = 0x0000000080803520
daif           = 0x00000000000002c0
mair_el3       = 0x00000000004404ff

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>