net: emaclite: drop the redeclaration of 'rc' & 'ret'
Drop the redeclaration of 'rc' & 'ret' due to the merge error to fix
below building error:
drivers/net/ethernet/xilinx/xilinx_emaclite.c:808:13: error : redeclaration of 'rc' with no linkage
|   808 |         int rc, ret;
|       |             ^~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>