LF-1162-10 gpu: drm: bridge: it6263: include correct headfile for DRM_ERROR
commit 122951e4700d1091c86e1dbea5749d86761c4b97 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/gpu/drm/bridge/it6263.c: In function ‘it6263_bridge_attach’:
../drivers/gpu/drm/bridge/it6263.c:729:3: error: implicit declaration of function ‘DRM_ERROR’; did you mean ‘DDC_ERROR’? [-Werror=implicit-function-declaration]
  729 |   DRM_ERROR("Fix bridge driver to make connector optional!");

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>