irqchip: imx-gpcv2: Fix build error for imx_v6_v7_defconfig
commit 501fcef208a1a0e4224c4c73a65a1968b5b6c7d4 from
https://source.codeaurora.org/external/imx/linux-imx

Fix below build error when built with imx_v6_v7_defconfig:

drivers/irqchip/irq-imx-gpcv2.c: In function 'imx_gpcv2_wake_request_fixup':
drivers/irqchip/irq-imx-gpcv2.c:112:28: error: '__smp_cross_call' undeclared (first use in this function); did you mean 'set_smp_cross_call'?
  __gic_v3_smp_cross_call = __smp_cross_call;
                            ^~~~~~~~~~~~~~~~
                            set_smp_cross_call
drivers/irqchip/irq-imx-gpcv2.c:112:28: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>