MLK-21876-4 ASoC: fsl: sai: fix build for next-20190524 upgrade
commit 2a635fc846224d82fcfa73cfdab969d2a2cfb484 from
https://source.codeaurora.org/external/imx/linux-imx

In file included from ../sound/soc/fsl/fsl_sai.c:15:0:
../sound/soc/fsl/fsl_sai.c: In function ‘fsl_sai_startup’:
../sound/soc/fsl/fsl_sai.c:957:51: error: ‘offset’ undeclared (first use in this function)
  regmap_update_bits(sai->regmap, FSL_SAI_xCR3(tx, offset),
                                                   ^
../include/linux/regmap.h:77:31: note: in definition of macro ‘regmap_update_bits’
  regmap_update_bits_base(map, reg, mask, val, NULL, false, false)
                               ^
../sound/soc/fsl/fsl_sai.h:84:37: note: in expansion of macro ‘FSL_SAI_TCR3’
 #define FSL_SAI_xCR3(tx, off) (tx ? FSL_SAI_TCR3(off) : FSL_SAI_RCR3(off))
                                     ^
../sound/soc/fsl/fsl_sai.c:957:34: note: in expansion of macro ‘FSL_SAI_xCR3’
  regmap_update_bits(sai->regmap, FSL_SAI_xCR3(tx, offset),
                                  ^
../sound/soc/fsl/fsl_sai.c:957:51: note: each undeclared identifier is reported only once for each function it appears in
  regmap_update_bits(sai->regmap, FSL_SAI_xCR3(tx, offset),
                                                   ^
../include/linux/regmap.h:77:31: note: in definition of macro ‘regmap_update_bits’
  regmap_update_bits_base(map, reg, mask, val, NULL, false, false)
                               ^
../sound/soc/fsl/fsl_sai.h:84:37: note: in expansion of macro ‘FSL_SAI_TCR3’
 #define FSL_SAI_xCR3(tx, off) (tx ? FSL_SAI_TCR3(off) : FSL_SAI_RCR3(off))
                                     ^
../sound/soc/fsl/fsl_sai.c:957:34: note: in expansion of macro ‘FSL_SAI_xCR3’
  regmap_update_bits(sai->regmap, FSL_SAI_xCR3(tx, offset),

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>