ASoC: fsl: imx-wm8962: fix build fix build for 5.1 RC kernel
commit 71f38f9ea0ac3670fbc1323f49d8fb5d63042809 from
https://source.codeaurora.org/external/imx/linux-imx

./sound/soc/fsl/imx-wm8962.c: In function 'hpjack_status_check':
../sound/soc/fsl/imx-wm8962.c:116:3: error: implicit declaration of function 'snd_soc_codec_get_dapm' [-Werror=implicit-function-declaration]
   snd_soc_dapm_disable_pin(snd_soc_codec_get_dapm(priv->codec), "Ext Spk");
   ^
../sound/soc/fsl/imx-wm8962.c:116:3: warning: passing argument 1 of 'snd_soc_dapm_disable_pin' makes pointer from integer without a cast
In file included from ../include/sound/soc.h:413:0,
                 from ../sound/soc/fsl/imx-wm8962.c:24:
../include/sound/soc-dapm.h:449:5: note: expected 'struct snd_soc_dapm_context *' but argument is of type 'int'
 int snd_soc_dapm_disable_pin(struct snd_soc_dapm_context *dapm,
     ^
../sound/soc/fsl/imx-wm8962.c:120:3: warning: passing argument 1 of 'snd_soc_dapm_enable_pin' makes pointer from integer without a cast
   snd_soc_dapm_enable_pin(snd_soc_codec_get_dapm(priv->codec), "Ext Spk");
   ^
In file included from ../include/sound/soc.h:413:0,
                 from ../sound/soc/fsl/imx-wm8962.c:24:
../include/sound/soc-dapm.h:445:5: note: expected 'struct snd_soc_dapm_context *' but argument is of type 'int'
 int snd_soc_dapm_enable_pin(struct snd_soc_dapm_context *dapm,
     ^
../sound/soc/fsl/imx-wm8962.c: In function 'micjack_status_check':
../sound/soc/fsl/imx-wm8962.c:147:3: error: implicit declaration of function 'snd_soc_update_bits' [-Werror=implicit-function-declaration]
   snd_soc_update_bits(priv->codec, WM8962_THREED1,
   ^
../sound/soc/fsl/imx-wm8962.c:161:3: warning: passing argument 1 of 'snd_soc_dapm_disable_pin' makes pointer from integer without a cast
   snd_soc_dapm_disable_pin(snd_soc_codec_get_dapm(priv->codec), "DMIC");
   ^
In file included from ../include/sound/soc.h:413:0,
                 from ../sound/soc/fsl/imx-wm8962.c:24:
../include/sound/soc-dapm.h:449:5: note: expected 'struct snd_soc_dapm_context *' but argument is of type 'int'
 int snd_soc_dapm_disable_pin(struct snd_soc_dapm_context *dapm,
     ^
../sound/soc/fsl/imx-wm8962.c:165:3: warning: passing argument 1 of 'snd_soc_dapm_enable_pin' makes pointer from integer without a cast
   snd_soc_dapm_enable_pin(snd_soc_codec_get_dapm(priv->codec), "DMIC");
   ^
In file included from ../include/sound/soc.h:413:0,
                 from ../sound/soc/fsl/imx-wm8962.c:24:
../include/sound/soc-dapm.h:445:5: note: expected 'struct snd_soc_dapm_context *' but argument is of type 'int'
 int snd_soc_dapm_enable_pin(struct snd_soc_dapm_context *dapm,
     ^
../sound/soc/fsl/imx-wm8962.c: In function 'imx_wm8962_gpio_init':
../sound/soc/fsl/imx-wm8962.c:441:41: error: 'struct snd_soc_dai' has no member named 'codec'
  struct snd_soc_codec *codec = codec_dai->codec;
                                         ^
cc1: some warnings being treated as errors
../scripts/Makefile.build:278: recipe for target 'sound/soc/fsl/imx-wm8962.o' failed

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>