MLK-21876-7 gpu: drm: dpu: fix build for next-20190524 upgrade
commit 586492f86e78d0889b6ca945216bc9192f3439a6 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/gpu/drm/imx/dpu/dpu-kms.c:23:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>