LF-1162-24 gpu: drm: gpu-viv: update the using of pud_offset
commit 605e937bf3b14506c48617d9f7b6578998c0dcc8 from
https://source.codeaurora.org/external/imx/linux-imx

pud_offset() changed since:
5d4d4a4a2866 ("arm/arm64: add support for folded p4d page tables")

  CC      drivers/mxc/gpu-viv/hal/os/linux/kernel/allocator/default/gc_hal_kernel_allocator_user_memory.o
In file included from ../arch/arm64/include/asm/thread_info.h:17,
                 from ../include/linux/thread_info.h:38,
                 from ../arch/arm64/include/asm/preempt.h:5,
                 from ../include/linux/preempt.h:78,
                 from ../include/linux/spinlock.h:51,
                 from ../include/linux/seqlock.h:36,
                 from ../include/linux/time.h:6,
                 from ../arch/arm64/include/asm/stat.h:12,
                 from ../include/linux/stat.h:6,
                 from ../include/linux/module.h:13,
                 from ../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_linux.h:61,
                 from ../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:56:
../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c: In function ‘_QueryProcessPageTable’:
../include/linux/compiler.h:284:2: error: incompatible type for argument 1 of ‘p4d_page_paddr’
  284 | ({         \
      | ~^~~~~~~~~~~
      |  |
      |  pgd_t {aka struct <anonymous>}
  285 |  union { typeof(x) __val; char __c[1]; } __u;   \
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  286 |  if (check)       \
      |  ~~~~~~~~~~~~~~~~~~
  287 |   __read_once_size(&(x), __u.__c, sizeof(x));  \
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  288 |  else        \
      |  ~~~~~~~~~~~~~
  289 |   __read_once_size_nocheck(&(x), __u.__c, sizeof(x)); \
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  290 |  smp_read_barrier_depends(); /* Enforce dependency ordering from x */ \
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  291 |  __u.__val;       \
      |  ~~~~~~~~~~~~~~~~~~
  292 | })
      | ~~
../arch/arm64/include/asm/memory.h:270:45: note: in definition of macro ‘__phys_to_virt’
  270 | #define __phys_to_virt(x) ((unsigned long)((x) - physvirt_offset))
      |                                             ^
../arch/arm64/include/asm/pgtable.h:634:42: note: in expansion of macro ‘__va’
  634 | #define pud_offset(dir, addr)  ((pud_t *)__va(pud_offset_phys((dir), (addr))))
      |                                          ^~~~
../include/linux/compiler.h:293:22: note: in expansion of macro ‘__READ_ONCE’
  293 | #define READ_ONCE(x) __READ_ONCE(x, 1)
      |                      ^~~~~~~~~~~
../arch/arm64/include/asm/pgtable.h:633:52: note: in expansion of macro ‘READ_ONCE’
  633 | #define pud_offset_phys(dir, addr) (p4d_page_paddr(READ_ONCE(*(dir))) + pud_index(addr) * sizeof(pud_t))
      |                                                    ^~~~~~~~~
../arch/arm64/include/asm/pgtable.h:634:47: note: in expansion of macro ‘pud_offset_phys’
  634 | #define pud_offset(dir, addr)  ((pud_t *)__va(pud_offset_phys((dir), (addr))))
      |                                               ^~~~~~~~~~~~~~~
../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:434:15: note: in expansion of macro ‘pud_offset’
  434 |         pud = pud_offset(pgd, logical);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>