MLK-13470 mfd: max17135: export symbols to fix build error as a module
commit 9202b784dda7bcc734736d03547b8908d15dea84 from
https://source.codeaurora.org/external/imx/linux-imx

export symbols to fix build error as a module:

ERROR: "max17135_reg_read" [drivers/hwmon/max17135-hwmon.ko] undefined!

Signed-off-by: Julien Olivain <julien.olivain@nxp.com>
Acked-by: Robby Cai <robby.cai@nxp.com>