MLK-21876-7 gpu: drm: dpu: fix build for next-20190524 upgrade
commit 99aa856532e877f794893f300331115e2ab36aa4 from
https://source.codeaurora.org/external/imx/linux-imx

../drivers/gpu/drm/imx/dpu/dpu-kms.c:23:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>