gpu:Remove dma.h to avoid Linux 5.x build problem
commit 08f009a33863a81d0976e4e25eafa05963c5b0e0 from
https://source.codeaurora.org/external/imx/linux-imx

Log:
    ../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:87:17:
fatal error: dma.h: No such file or directory
     #include <dma.h>
                     ^
    compilation terminated.
    ../scripts/Makefile.build:280: recipe for target
'drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.o' failed
    make[4]: ***
[drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.o] Error 1

Signed-off-by: Minjie Zhuang<minjie.zhuang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>