MGS-4530-2 disable busfreq-imx to fix L4.19 dash build
commit cb554c92bf258d63df6f32a8275adcc6624b8947 from
https://source.codeaurora.org/external/imx/linux-imx

gc_hal_kernel_platform_imx.c:90:14: fatal error: linux/busfreq-imx.h: No such file or directory
 #    include <linux/busfreq-imx.h>

Signed-off-by: Xianzhong <xianzhong.li@nxp.com>