MLK-23547: ASoC: SOF: Use machine_drv_name on OF platforms
commit 27d28aff5270c64ef59baa7009c73f960bc20be2 from
https://source.codeaurora.org/external/imx/linux-imx

On OF platforms information about machine driver is stored
in sof_pdata->machine_drv_name.

Without this SOF probe fails with:
error: no matching ASoC machine driver found - aborting probe

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>