LF-1011-33 media: capture: mxc_v4l2: remove using of ns_to_timeval
commit 14b3a32596975db32e25b02f78a08f09beb72f77 from
https://source.codeaurora.org/external/imx/linux-imx

This API was removed.

../drivers/media/platform/mxc/capture/mxc_v4l2_capture.c: In function ‘camera_callback’:
../drivers/media/platform/mxc/capture/mxc_v4l2_capture.c:2563:4: error: implicit declaration of function ‘ns_to_timeval’; did you mean ‘ns_to_ktime’? [-Werror=implicit-function-declaration]
 2563 |    ns_to_timeval(ts.tv_sec * 1000000000ULL + ts.tv_nsec);
      |    ^~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>